// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{
    public partial class MainEntryPoint
    {
        [Inject] private readonly IObjectResolver _resolver;
        
        [Inject] private readonly GameHandler _gameHandler;
        [Inject] private readonly UpdateHandler _updateHandler;

        partial void Init()
        {
            _gameHandler?.Init();
            _updateHandler?.Init();
        }
    }
}
