// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using UnityEngine;
using MessagePipe;
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{
    public partial class MainLifetimeScope
    {
        [SerializeField] private MainConfig _mainConfig;
        protected override void Configure(IContainerBuilder builder)
        {
            base.Configure(builder);
        
            if (_mainConfig != null) builder.RegisterInstance(_mainConfig);
            builder.Register<GameHandler>(Lifetime.Scoped);
            builder.Register<UpdateHandler>(Lifetime.Scoped);
            var options = builder.RegisterMessagePipe();
            builder.RegisterMessageBroker<ModelLoopMessage>(options);
            builder.RegisterMessageBroker<UpdateMessage>(options);
            builder.RegisterEntryPoint<MainEntryPoint>();
        }
    }
}
