// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.GalaxyInBottles
{
    public partial class RootEntryPoint
    {
        [Inject] private IObjectResolver Resolver { get; set; }
        
        [Inject] private SettingStore<ItemSetting> ItemSettingStore { get; set; }
        [Inject] private ItemSetting[] ItemSettings { get; set; }

        partial void Init()
        {
            if (ItemSettings != null) ItemSettingStore?.Init(ItemSettings);
        }
    }
}
