// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.GalaxyInBottles
{
    public partial class RootEntryPoint
    {
        [Inject] private readonly IObjectResolver _resolver;
        
        [Inject] private readonly SettingStore<ItemSetting> _itemSettingStore;
        [Inject] private readonly ItemSetting[] _itemSettings;

        partial void Init()
        {
            if (_itemSettings != null) _itemSettingStore?.Init(_itemSettings);
        }
    }
}
