// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.GalaxyInBottles
{
    public partial class SandboxEntryPoint
    {
        [Inject] private readonly IObjectResolver _resolver;
        
        [Inject] private readonly SandboxHandler _sandboxHandler;
        [Inject] private readonly UpdateHandler _updateHandler;

        partial void Init()
        {
            _sandboxHandler?.Init();
            _updateHandler?.Init();
        }
    }
}
