// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using UnityEngine;
using MessagePipe;
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{
    public partial class SandboxLifetimeScope
    {
        [SerializeField] private SandboxConfig _sandboxConfig;
    
        protected override void Configure(IContainerBuilder builder)
        {
            base.Configure(builder);
        
            if (_sandboxConfig != null) builder.RegisterInstance(_sandboxConfig);
            builder.Register<SandboxHandler>(Lifetime.Scoped);
            builder.Register<UpdateHandler>(Lifetime.Scoped);
            var options = builder.RegisterMessagePipe();
            builder.RegisterMessageBroker<ModelLoopMessage>(options);
            builder.RegisterMessageBroker<UpdateMessage>(options);
            builder.RegisterEntryPoint<SandboxEntryPoint>();
        }
    }
}
