// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.GalaxyInBottles
{
    public partial class SandboxEntryPoint
    {
        [Inject] private IObjectResolver Resolver { get; set; }
        
        [Inject] private SandboxHandler SandboxHandler { get; set; }
        [Inject] private UpdateHandler UpdateHandler { get; set; }

        partial void Init()
        {
            SandboxHandler?.Init();
            UpdateHandler?.Init();
        }
    }
}
