// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using VContainer;

namespace tana_gh.GalaxyInBottles
{
    public partial class StoreHouseEntryPoint
    {
        [Inject] private readonly IObjectResolver _resolver;
        

        partial void Init()
        {
        }
    }
}
