// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using UnityEngine;
using MessagePipe;
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{
    public partial class UILifetimeScope
    {
    
        protected override void Configure(IContainerBuilder builder)
        {
            base.Configure(builder);
        
            builder.RegisterEntryPoint<UIEntryPoint>();
        }
    }
}
