using System;
using System.Collections.Generic;
using System.Linq;
using tana_gh.UnityDotG.Editor;

namespace tana_gh.GalaxyInBottles.Editor
{
    [CodeGen]
    public class EntryPointCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            context.AutoGeneratedFolder = UnityDotGConstants.autoGeneratedFolder;

            var handlers = RoleAttributeUtil.GetAllTypesWithRole("Handler");
            foreach (var name in UnityDotGConstants.sceneNames)
            {
                GenerateOne(context, name, handlers);
            }
        }

        public static void GenerateOne(CodeGenContext context, string name, IEnumerable<Type> handlers)
        {
            context.AddCode($"{name}EntryPoint.g.cs",
$@"
using VContainer;

namespace tana_gh.GalaxyInBottles
{{
    public partial class {name}EntryPoint
    {{
        [Inject] private readonly IObjectResolver _resolver;
        {
            handlers
            .Select(handler => $@"[Inject] private readonly {handler.GetTypeName()} {handler.GetVarName()};")
            .ToLines(8)
        }

        partial void Init()
        {{{
            handlers
            .Select(handler => $@"{handler.GetVarName()}?.Init();")
            .ToLines(12)
        }
        }}
    }}
}}
"
            );
        }
    }
}
