using tana_gh.UnityDotG.Editor;

namespace tana_gh.GalaxyInBottles.Editor
{
    [CodeGen]
    public class FarmEntryPointCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            context.AutoGeneratedFolder = UnityDotGConstants.autoGeneratedFolder;
            context.AddCode("FarmEntryPoint.g.cs",
$@"
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{{
    public partial class FarmEntryPoint
    {{
        [Inject] private readonly IObjectResolver _resolver;

        partial void Init()
        {{
        }}
    }}
}}
"
            );
        }
    }
}
