using System.Linq;
using tana_gh.UnityDotG.Editor;

namespace tana_gh.GalaxyInBottles.Editor
{
    [CodeGen]
    public class FarmEntryPointCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            var handlers = TypeAttributeUtil.GetAllTypesWithAttribute<HandlerAttribute>();

            context.AutoGeneratedFolder = UnityDotGConstants.autoGeneratedFolder;
            context.AddCode("FarmEntryPoint.g.cs",
$@"
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{{
    public partial class FarmEntryPoint
    {{
        [Inject] private readonly IObjectResolver _resolver;
        {
            handlers
            .Select(handler => $@"[Inject] private readonly {handler.GetTypeName()} {handler.GetVarName()};")
            .ToLines(8)
        }

        partial void Init()
        {{{
            handlers
            .Select(handler => $@"{handler.GetVarName()}?.Init();")
            .ToLines(12)
        }
        }}
    }}
}}
"
            );
        }
    }
}
