using tana_gh.UnityDotG.Editor;

namespace tana_gh.GalaxyInBottles.Editor
{
    [CodeGen]
    public class FarmLifetimeScopeCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            context.AutoGeneratedFolder = UnityDotGConstants.autoGeneratedFolder;
            context.AddCode("FarmLifetimeScope.g.cs",
$@"
using UnityEngine;
using MessagePipe;
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{{
    public partial class FarmLifetimeScope
    {{
        protected override void Configure(IContainerBuilder builder)
        {{
            base.Configure(builder);
        }}
    }}
}}
"
            );
        }
    }
}
