using System;
using System.Linq;
using tana_gh.UnityDotG.Editor;

namespace tana_gh.GalaxyInBottles.Editor
{
    [CodeGen]
    public class SandboxLifetimeScopeCodeGen
    {
        public static void Generate(CodeGenContext context)
        {
            context.AutoGeneratedFolder = UnityDotGConstants.autoGeneratedFolder;

            foreach (var sceneKind in Enum.GetValues(typeof(SceneKind)).Cast<SceneKind>())
            {
                GenerateOne(context, sceneKind);
            }
        }

        public static void GenerateOne(CodeGenContext context, SceneKind sceneKind)
        {
            var settings = RoleAttributeUtil.GetAllTypesWithRole("Setting", sceneKind);
            var settingArrays = RoleAttributeUtil.GetAllTypesWithRole("SettingArray", sceneKind);
            var handlers = RoleAttributeUtil.GetAllTypesWithRole("Handler", sceneKind);
            var messages = RoleAttributeUtil.GetAllTypesWithRole("Message", sceneKind);

            context.AddCode($"{sceneKind}LifetimeScope.g.cs",
$@"
using UnityEngine;
using MessagePipe;
using VContainer;
using VContainer.Unity;

namespace tana_gh.GalaxyInBottles
{{
    public partial class {sceneKind}LifetimeScope
    {{{
        settings
        .Select(setting => $@"[SerializeField] private {setting.GetTypeName()} {setting.GetVarName()};")
        .ToLines(8)
    }{
        settingArrays
        .Select(settings => $@"[SerializeField] private {settings.GetTypeName()}[] {settings.GetArrayVarName()};")
        .ToLines(8)
    }
    
        protected override void Configure(IContainerBuilder builder)
        {{
            base.Configure(builder);
        {
            settings
            .Select(setting => $@"if ({setting.GetVarName()} != null) builder.RegisterInstance({setting.GetVarName()});")
            .ToLines(12)
        }{
            settingArrays
            .Select(settings => $@"if ({settings.GetArrayVarName()} != null) builder.RegisterInstance({settings.GetArrayVarName()});")
            .ToLines(12)
        }{
            handlers
            .Select(handler => $@"builder.Register<{handler.GetTypeName()}>(Lifetime.Scoped);")
            .ToLines(12)
        }{
            (messages.Any() ? new string[] { $@"var options = builder.RegisterMessagePipe();" } : Enumerable.Empty<string>())
            .Concat(
                messages
                .Select(message => $@"builder.RegisterMessageBroker<{message.GetTypeName()}>(options);")
            )
            .ToLines(12)
        }
            builder.RegisterEntryPoint<{sceneKind}EntryPoint>();
        }}
    }}
}}
"
            );
        }
    }
}
