using System;

namespace tana_gh.GalaxyInBottles.Editor
{
    public class UnityDotGConstants
    {
        public static readonly string autoGeneratedFolder = "Assets/GalaxyInBottles/Runtime/UnityDotG/AutoGenerated";
        public static readonly string[] sceneNames = new string[] { "Root", "Sandbox", "UI" };
    }
}
