
namespace tana_gh.GalaxyInBottles.Editor
{
    public class UnityDotGConstants
    {
        public static readonly string autoGeneratedFolder = "Assets/GalaxyInBottles/Runtime/UnityDotG/AutoGenerated";
    }
}
