using System;

namespace tana_gh.GalaxyInBottles.Editor
{
    public class UnityDotGConstants
    {
        public static string AutoGeneratedFolder { get; } = "Assets/GalaxyInBottles/Runtime/UnityDotG/AutoGenerated";
    }
}
